export const questions=[
   "Q1 ) What is the basic unit of data transfer in networks?",
   "Q2 ) Which layer of the OSI model is responsible for physical addressing and cable transmission?",
   "Q3 )What is the difference between TCP and UDP?",
   "Q4 ) What type of medium is most susceptible to electromagnetic interference?",
   "Q5 ) Which protocol is used for routing data packets across the internet?",
   "Q6 )What is the purpose of a firewall?",
   "Q7 ) What is the main difference between a LAN and a WAN?",
   "Q8 )What is the advantage of using Wi-Fi over Bluetooth?",
   "Q9 ) What is the purpose of a MAC address?",
   "Q10 ) What is the difference between analog and digital signals?",
   "Q11 ) What is the purpose of a repeater?",
   "Q12 ) What is the main advantage of using a switch over a hub?",
   "Q13 ) What is the function of a DNS server?",
   "Q14 ) Which type of attack attempts to gain unauthorized access to a computer system by exploiting vulnerabilities?",
   "Q15 ) What is the purpose of a VPN?  ",
   "Q16 )  What type of network topology connects all devices directly to a central hub or switch?",
   "Q17 ) What is the main difference between HTTP and HTTPS ",
   "Q18 ) What is the purpose of a router in a network?",
   "Q19 ) What is the main advantage of using fiber optic cables over copper cables for data transmission?",
   "Q20 ) What is the purpose of a checksum in a data packet?",
   "Q21 ) In BGP routing, the AS-PATH attribute does which of the following:?",
   "Q22 ) Multicast routing protocols like PIM-SM has the main responsibility of :- ",
   "Q23 ) What is the main task of Software-defined network (SDN) controllers:?",
   "Q24 )  The main benefit of network function virtualization (NFV) is:- ",
   "Q25 ) A major challenge of BGP scalability is: ",
   "Q26 )  In a content delivery network (CDN), edge servers primarily: ",
   "Q27 )  A key metric for assessing network performance in data centers is: ",
   "Q28 ) One disadvantage of SDN compared to traditional networking is: ",
   "Q29 ) A technique for optimizing network traffic flow based on application priorities is called: ",
   "Q30 )  Which emerging technology poses significant security challenges for advanced networks?",
   "Q31 ) . Which layer of the OSI model is responsible for error detection and correction in data transmission ",
   "Q32 )  Which layer of the OSI model defines the format and structure of data for application-specific purposes?",
   "Q33 ) Which layer of the OSI model defines the addressing scheme for routing packets across networks?",
   "Q34 )  Which layer of the OSI model defines the physical characteristics of the transmission medium and signal encoding?",
   "Q35 ) The TCP protocol operates at which layer of the OSI model?",
   "Q36 ) The UDP protocol operates at which layer of the OSI model?",
   "Q37 ) Which OSI layer protocol is responsible for establishing, managing, and terminating sessions between communicating applications?",
   "Q38 )  What is the primary function of the Data Link layer in the OSI model?",
   "Q39 ) Which OSI layer protocol is responsible for addressing individual devices on a network segment?",
   "Q40 ) Which OSI layer protocol is responsible for breaking down data into manageable packets for transmission?",
   "Q41 ) Which OSI layer deals with error detection and correction in data transmission?",
   "Q42 )  Which OSI layer defines the format and structure of data for application-specific purposes?",
   "Q43 ) What is the main function of the Session layer in the OSI model?",
   "Q44 )  Which OSI layer protocol specifies the logical addressing scheme for routing packets across networks?",
   "Q45 ) Which OSI layer defines the physical characteristics of the transmission medium and signal encoding?",
   "Q46 ) At which OSI layer does TCP operate?",
   "Q47 ) What type of data transfer does UDP provide at the Transport layer?",
   "Q48 ) Which layer of the OSI model is responsible for data framing and error detection within a network segment?",
   "Q49 ) What is the primary function of a hub in data communication?",
   "Q50 ) How does a switch differ from a hub in terms of data transmission?",
   "Q51 ) What is the main function of a router in a network?",
   "Q52 ) What type of device converts IP addresses to MAC addresses for data transmission within a network segment?",
   "Q53 ) What is the main purpose of a firewall in a network?",
   "Q54 ) What is the difference between a modem and a router?",
   "Q55 ) Which OSI layer deals with encryption and decryption of data for secure communication?",
   "Q56 ) What protocol defines the format and encoding of multimedia content like images and videos?",
   "Q57 ) Which OSI layer protocol facilitates reliable file transfer with progress tracking?",
   "Q58 ) How does the Data Link layer utilize checksums to ensure data integrity?",
   "Q59 ) What is the main difference between datagrams and virtual circuits in Transport layer protocols?",
   "Q60 )What is the role of port numbers in Transport layer protocols like TCP and UDP?",
   "Q61 ) How do access points (APs) function in wireless networks?",
   "Q62 ) What is the main drawback of using a hub compared to a switch in a network?",
   "Q63 ) What is the purpose of a virtual LAN (VLAN) in a network?",
   "Q64 ) Which type of network device acts as a central point for managing network security policies and access control?",
   "Q65 ) What is the role of a load balancer in a network environment?",
   "Q66 ) Which OSI layer ensures data synchronization and flow control between communicating applications?",
   "Q67 )  What protocol facilitates email communication on the internet?",
   "Q68 ) How does the Network layer determine the best path for routing data packets?",
   "Q69 ) What is the role of the Domain Name System (DNS) in the internet?",
   "Q70 ) What type of encryption utilizes public and private keys for secure communication?", 
   "Q71 ) What does a repeater do in a network?",
   "Q72 ) What is the main difference between a wireless LAN (WLAN) and a Wide Area Network (WAN)?",
   "Q73 ) How does a Network Address Translation (NAT) device hide the internal IP addresses of a network from the internet?",
   "Q74 ) What is the purpose of a VPN (Virtual Private Network)?",
   "Q75 ) Which type of intrusion detection system (IDS) monitors network traffic for suspicious activity and potential security threats?",
   "Q76 ) Which Transport layer protocol provides reliable, connection-oriented data transfer with sequencing and error checking?",
   "Q77 ) Which Transport layer protocol offers fast, connectionless data transfer without guaranteed delivery or error correction?",
   "Q78 ) What does TCP use to ensure reliable data delivery and prevent packet loss?",
   "Q79 ) Which feature of UDP makes it suitable for streaming media applications like voice and video communication?",
   "Q80 ) What port number is typically used by HTTP traffic on the Transport layer?",
   "Q81 ) How does SCTP (Stream Control Transmission Protocol) differentiate itself from TCP and UDP?",
   "Q82 ) What term refers to the maximum amount of data a receiver can buffer before requesting the sender to slow down transmission?",
   "Q83 )  How does TCP handle congestion in the network and avoid overwhelming receivers with data?",
   "Q84 ) What is the role of port numbers in Transport layer protocols?",
   "Q85 )  How do firewalls utilize Transport layer protocols for security purposes?",
   "Q86 )  Which Transport layer protocol is commonly used for file transfer applications like FTP and SCP?",
   "Q87 ) What protocol is primarily used for email communication on the internet?",
   "Q88 ) How does VoIP (Voice over IP) utilize the Transport layer to transmit voice data packets?",
   "Q89 ) What challenges does video conferencing pose for Transport layer protocols due to its real-time nature?",
   "Q90 )What optimization techniques can be employed at the Transport layer to improve video streaming performance?", 
   "Q91 ) In what scenario might a three-way, plus handshake be used instead of a standard three-way handshake for TCP connection establishment?",
   "Q92 ) How does the Time-Wait state in TCP relate to the four-way handshake and prevent unintended connection re-establishment?",
   "Q93 ) What is the purpose of TCP window scaling in Transport layer communication?",
   "Q94 ) What potential drawbacks are associated with using large window sizes in TCP window scaling?",
   "Q95 ) How does the CUBIC congestion control algorithm differ from traditional TCP algorithms like Vegas or Reno?",
   "Q96 ) What are the benefits of using Compound TCP congestion control compared to standard TCP for high-speed networks?",
   "Q97 ) What key features does DTLS (Datagram Transport Layer Security) offer for securing UDP communication compared to standard TLS over TCP?",
   "Q98 ) What are some potential challenges associated with using DTLS compared to TLS over TCP for secure communication?",
   "Q99 ) What is the primary advantage of using SCTP (Stream Control Transmission Protocol) over TCP for reliable multicast data transfer?",
   "Q100 ) What challenges arise when implementing reliable multicast data transfer in the Transport layer compared to unicasting?",

    ]
    