export const questions=[
     "Q1) Which of the following regional languages is the most popular for online content consumption in India  ?",
     "Q2) Which social media platform has the largest user base in India  ?",
     "Q3) What is the most popular e-commerce platform in India  ?",
     "Q4)  Which Indian festival sees the highest spike in online shopping activity  ?",
     "Q5)  Which of the following is NOT considered a good practice for SEO in India  ?",
     "Q6)  What is the name of the Indian government's initiative to promote digital literacy and internet access in rural areas  ?",
     "Q7)  Which type of mobile marketing campaign would be most effective for reaching rural audiences in India  ?",
     "Q8)  What is a challenge faced by many digital marketers in India when targeting regional audiences  ?",
     "Q9)  Which Indian content format has seen a surge in popularity for promoting brands and products  ?",
     "Q10) What is a unique opportunity for digital marketers in India when leveraging social media  ?",
     "Q11)  How can digital marketing be used to address social and environmental issues in India  ?",
     "Q12) What is the primary reason for the rapid growth of e-commerce in India  ?",
     "Q13)  Which Indian city is considered the leading hub for startups and digital innovation  ?",
     "Q14)  What is a crucial factor for building brand trust in the Indian online market  ?",
     "Q15)  Which popular regional language has shown significant potential for voice search in India  ?",
     "Q16) What is a major concern for mobile marketing campaigns in India regarding data privacy  ?",
     "Q17) Which digital payment method is gaining traction in rural areas of India  ?",
     "Q18) What is a potential barrier to online learning initiatives in India  ?",
     "Q19) Which social media platform is primarily used for professional networking in India  ?",
     "Q20) How can influencer marketing be effectively adapted for the Indian market  ?",
     "Q21) What is a growing trend in digital marketing for targeting Gen Z consumers in India  ?",
     "Q22) What is a challenge faced by digital marketers when measuring the effectiveness of their campaigns in India  ?",
     "Q23) How can brands effectively integrate vernacular languages into their digital marketing strategies  ?",
     "Q24) What is a growing concern for online advertisers in India  ?",
     "Q25) Which Indian government initiative aims to develop digital infrastructure and services across the country  ?",
     "Q26) How can digital marketing be used to empower small businesses in India  ?",
     "Q27) What are some ethical considerations for digital marketing in India  ?",
     "Q28) What is a key factor for successful content marketing in the Indian market  ?",
     "Q29) How can brands leverage the power of storytelling in their digital marketing  ?",
     "Q30) Which emerging technology holds promise for the future of digital marketing in India  ?",
     "Q31) What is the key to success for digital marketers in the dynamic and evolving Indian market  ?",
     "Q32) What is the most popular content format for online learning in India  ?",
     "Q33)  Which social media platform is primarily used for news consumption in India  ?",
     "Q34) What is a challenge faced by online businesses in India regarding logistics and delivery  ?",
     "Q35) Which Indian e-commerce platform focuses on selling handicrafts and traditional products  ?",
     "Q36) How can AI be effectively used in digital marketing campaigns in India  ?",
     "Q37)  What is a potential opportunity for digital marketing in rural India  ?",
     "Q38) Which regional language has seen a rising adoption of voice assistants in India  ?",
     "Q39) What is a growing trend in influencer marketing in India  ?",
     "Q40) How can brands effectively engage with Gen Z consumers on social media in India  ?",
     "Q41) What is a challenge faced by digital marketers when targeting millennials in India  ?",
     "Q42) How can brands leverage vernacular languages in their online customer service strategies  ?",
     "Q43) What is a growing concern for digital marketers in India regarding consumer privacy  ?",
     "Q44) How can brands utilize Augmented Reality (AR) for marketing campaigns in India  ?",
     "Q45) What is a challenge faced by digital content creators in India regarding copyright and intellectual property  ?",
     "Q46) How can brands effectively engage with the LGBTQ+ community in India through digital marketing  ?",
     "Q47) What is a growing trend in online dating and matchmaking in India  ?",
     "Q48) How can digital marketing be used to promote sustainable living practices in India  ?",
     "Q49) What is a challenge faced by online education platforms in India regarding accessibility and equity  ?",
     "Q50) How can brands effectively integrate regional food culture into their digital marketing campaigns  ?",
     "Q51) What is a challenge faced by digital health platforms in India regarding data security and privacy  ?",
     "Q52) How can digital marketing be used to promote awareness about mental health in India  ?",
     "Q53) What is a growing trend in online content consumption in India  ?",
     "Q54) How can brands effectively measure the impact of their digital marketing campaigns in a crowded online space  ?",
     "Q55) Which regional language has seen a surge in popularity for online gaming in India  ?",
     "Q56) How can brands incorporate ethical and sustainable practices into their digital marketing strategies  ?",
     "Q57) What is a challenge faced by social media influencers in India regarding brand partnerships and endorsements  ?",
     "Q58) How can digital marketing be used to empower women entrepreneurs in India  ?",
     "Q59) What is a growing concern for data-driven marketing in India regarding data privacy and security  ?",
     "Q60) How can brands effectively leverage virtual reality (VR) for marketing campaigns in India  ?",
     "Q61) What is the fundamental unit of data in transmission  ?",
     "Q62) Which layer of the OSI model is responsible for physical addressing and cable transmission  ?",
     "Q63) What is the difference between TCP and UDP  ?",
     "Q64) What type of medium is most susceptible to electromagnetic interference  ?",
     "Q65) Which protocol is used for routing data packets across the internet  ?",
     "Q66) What is the purpose of a firewall  ?",
     "Q67) What is the main difference between a LAN and a WAN  ?",
     "Q68) What is the main advantage of using Wi-Fi over Bluetooth  ?",
     "Q69) What is the purpose of a MAC address  ?",
     "Q70) What is the difference between analog and digital signals  ?",
     "Q71) What is the purpose of a repeater  ?",
     "Q72) What is the main advantage of using a switch over a hub  ?",
     "Q73) Which type of cable offers the highest bandwidth and is least susceptible to interference  ?",
     "Q74) What is the term for the process of breaking down data into smaller, manageable units for transmission  ?",
     "Q75) What is the difference between symmetric and asymmetric internet connections  ?",
     "Q76) What is the purpose of error detection and correction techniques in data communication  ?",
     "Q77) Which protocol is used for transferring files over the internet  ?",
     "Q78) What is the main difference between circuit switching and packet switching  ?",
     "Q79) What is the purpose of a virtual LAN (VLAN)  ?",
     "Q80) What is the basic unit of measurement for data transfer rates  ?",
     "Q81) What is the purpose of a demultiplexer  ?",
     "Q82) What is the difference between synchronous and asynchronous transmission  ?",
     "Q83) What is the main drawback of using wireless networks compared to wired networks  ?",
     "Q84) What is the basic unit of data processing in a CPU  ?",
     "Q85) What type of addressing mode uses a base register and an offset value to locate data in memory  ?",
     "Q86) Which instruction format typically encodes the operation code and operands within a single word  ?",
     "Q87) What is the purpose of a program counter (PC) in a CPU  ?",
     "Q88)What is the main advantage of using virtual memory in a computer system?",
     "Q89) What is the difference between synchronous and asynchronous DRAM architectures  ?",
     "Q90) What is the main function of a memory controller in a computer system  ?",
     "Q91) What type of instruction pipeline stage involves decoding the instruction and determining its operation  ?",
     "Q92) What is the purpose of branch prediction in a CPU  ?",
     "Q93) What are the main advantages of using multi-core architectures in CPUs  ?",
     "Q94) What hardware component is primarily responsible for managing the flow of data between the CPU, memory, and peripherals  ?",
     "Q95) How does superscalar architecture enhance CPU performance compared to traditional scalar architecture  ?",
     "Q96) What is the key difference between speculative execution and branch prediction in CPU pipelines  ?",
     "Q97) Which type of memory organization scheme utilizes non-contiguous memory segments instead of a linear address space  ?",
     "Q98) What is the primary advantage of using vector processing compared to scalar processing for specific workloads  ?",
     "Q99) What is the main purpose of a Translation Lookaside Buffer (TLB) in a virtual memory system  ?",
     "Q100) What is the key difference between L1 cache and L2 cache in a CPU memory hierarchy  ?",
    
]

 
