export const questions=[
    "Q1) Which component performs mathematical calculations and executes computer instructions?",
    "Q2) What type of storage is temporary and cleared when the computer shuts down?",
    "Q3) A device that converts digital data into sound is called a:",
    "Q4) The main circuit board that connects all other components within a computer is called the:",
    "Q5)  Which device is used to store large amounts of permanent data?",
    "Q6)  What type of memory is slow but inexpensive and widely used for permanent storage?",
    "Q7)  A device that allows you to point and click on the computer screen is called a:",
    "Q8) What is the process of moving data from a secondary storage device like a hard drive to RAM called?",
    "Q9) Which component is responsible for displaying video content on the screen?",
    "Q10) . What does BIOS stand for?",
    "Q11)  What is the difference between RAM and ROM?",
    "Q12)  How is data measured in computers?",
    "Q13) What is a USB port used for?",
    "Q14) What is the difference between an SSD and a HDD?",
    "Q15) What is a CPU socket?",
    "Q16) What does DPI stand for?",
    "Q17 What is a firewall?",
    "Q18) What does overclocking mean?",
    "Q19) What is a virus?",
    "Q20) What is a headphone jack used for?",
    "Q21) What are the main types of computer motherboards?",
    "Q22) What is the purpose of a graphics processing unit (GPU)?",
    "Q23) What is the difference between a laptop and a desktop computer?",
    "Q24) What is a cloud service?",
    "Q25)   What is a power supply unit (PSU) used for?",
    "Q26) What is a fan used for in a computer?",
    "Q27) What is the purpose of a thermal paste?",
    "Q28) What is a router used for?",
    "Q29) What is a modem used for?",
    "Q30) What is a BIOS password used for?",
    "Q31) Which component is often referred to as the brain of the computer?",
    "Q32) What type of device converts text and images into electrical signals that the computer can understand?",
    "Q33) What is the main function of a power supply unit (PSU)?",
    "Q34) What does the acronym HDMI stand for?",
    "Q35) What is the primary purpose of a cooling fan in a computer?",
    "Q36) Which type of storage device is typically faster but more expensive than a hard disk drive (HDD)?",
    "Q37) What does the abbreviation USB stand for?", 
    "Q38) What is the primary function of a graphics card?", 
    "Q39) What type of connector is commonly used to connect a monitor to a computer?",
    "Q40) What is the purpose of a webcam?",
    "Q41) What is the role of the BIOS in a computer?",
    "Q42) What does the acronym SATA stand for?",
    "Q43)  How do you measure the speed of a processor?",
    "Q44) What is the difference between a wired and a wireless mouse?",
    "Q45)  What is the purpose of a heat sink in a computer?",
    "Q46)  What does the acronym GPU stand for?",
    "Q47) What type of memory is volatile and loses its data when the computer is turned off?",
    "Q48) What is the main difference between a laptop and a desktop computer? ",
    "Q49) What is the purpose of a firewall in a computer?",
    "Q50) What type of device displays information on the screen?",
    "Q51) What device acts as the central hub for connecting all other components within a computer? ",
    "Q52) What type of memory is non-volatile and retains its data even when the computer is turned off?",
    "Q53) What are the two main types of desktop computer cases?",
    "Q54) What is the purpose of a Wi-Fi adapter in a computer?",
    "Q55) What does the acronym CPU stand for?",
    "Q56) What does the term bottleneck mean in the context of computer hardware?",
    "Q57)  How does a computer's BIOS interact with the operating system?",
    "Q58)  What is the advantage of using a solid-state drive (SSD) over a traditional hard disk drive (HDD)?",
    "Q59)  What type of device typically converts digital data into sound that we can hear?",
    "Q60)   What is the primary function of a thermal paste in a computer?",
    "Q61)  Which component acts as the computer's conductor, orchestrating communication between other parts?",
    "Q62)  What type of memory can be compared to a temporary notepad, losing its contents when power is lost?",
    "Q63) What are the two dominant categories of desktop computer form factors?",
    "Q64) How does a Wi-Fi adapter liberate your computer from the shackles of cables?",
    "Q65) What does the acronym CPU stand for, revealing its essential role in the computational dance?",
    "Q66) When a component in the hardware orchestra stumbles, causing performance to lag, what do we call this bottleneck?",
    "Q67) How does the BIOS act as a stagehand before the operating system takes center stage?",
    "Q68)  Why do solid-state drives (SSDs) dance circles around traditional hard disk drives (HDDs) in terms of speed?",
    "Q69)  Which hardware maestro transforms digital notes into the symphony of sound we hear?",
    "Q70)  What thermal magic trick does thermal paste perform, keeping the CPU cool and collected?",
    "Q71) Which component acts as the orchestra conductor, directing data flow between parts of the computer?",
    "Q72) What type of memory acts as a volatile notepad, losing its content when the power goes out?",
    "Q73) What are the two main categories of desktop computer sizes?",
    "Q74) How does a Wi-Fi adapter liberate your computer from the tethers of cables?",
    "Q75) What does the acronym CPU stand for, revealing its essential role in computational tasks?",
    "Q76) When a hardware component becomes the bottleneck, slowing down the entire system's performance, what do we call it?",
    "Q77) How does the BIOS act as the pre-show crew, preparing the stage before the operating system takes over?", 
    "Q78) Why do solid-state drives (SSDs) outperform traditional hard disk drives (HDDs) in terms of speed?",
    "Q79) Which hardware musician transforms digital data into the melodies and harmonies we hear?",
    "Q80) What thermal trick does thermal paste perform, keeping the CPU cool under pressure?",
    "Q81) Which component houses and connects all other internal parts, playing the role of the computer's real estate agent?",
    "Q82) What type of memory remembers settings and basic system information even when the computer is off, like a persistent digital notepad?",
    "Q83) How do laptops and desktops differ in terms of portability and power supply dependence?",
    "Q84) What does the acronym GPU stand for, revealing its specialization in graphical tasks?",
    "Q85) When data flows through the computer like a river, what bridges connect different components to ensure smooth communication?",
    "Q86) How does thermal paste act like a superhero's heat shield, protecting the CPU from overheating?",
    "Q87) What does the acronym BIOS stand for, hinting at its vital pre-boot role?",
    "Q88) How does a keyboard transform our physical keystrokes into digital signals the computer can understand?",
    "Q89) What type of storage device offers incredibly fast access speeds but tends to be more expensive and have limited capacity?",
    "Q90) How does a mouse translate our hand movements into precise cursor control on the screen?",
    "Q91) Which component acts as the brain of the computer, handling complex calculations and running software?",
    "Q92) What type of memory acts like a short-term cache, storing frequently used data for faster access?",
    "Q93) What are the two main form factors for desktop computer cases, catering to different size and performance needs?",
    "Q94) How does a Bluetooth adapter free your computer from the constraints of cables and wires?",
    "Q95) What does the acronym RAM stand for, reflecting its vital role in the temporary storage of data?",
    "Q96) When a component slows down the entire system, acting as a performance bottleneck, what do we call it?",
    "Q97) How does the BIOS act as the initial conductor before the operating system takes over, initializing hardware and preparing the system for boot?",
    "Q98) Why are solid-state drives (SSDs) so much faster than traditional hard disk drives (HDDs) in terms of boot times and application loading?",
    "Q99) Which peripheral device translates sound waves into digital signals the computer can understand?",
    "Q100) What thermal paste trick helps keep the CPU cool under pressure, preventing overheating and potential damage?",
    ]
    