export const questions=[
    "Q1) What is the difference between physical memory and virtual memory? ",
    "Q2) What is the purpose of a memory address?",
    "Q3) What is the role of a memory management unit (MMU) in a computer system? ",
    "Q4) What are the two main categories of memory allocation techniques? ",
    "Q5) Define fragmentation and its impact on memory management.",
    "Q6) What is a garbage collector and how does it function? ",
    "Q7) Explain the difference between reference counting and mark-and-sweep garbage collection techniques. ",
    "Q8) What are some strategies for optimizing memory usage in programs? ",
    "Q9) Compare and contrast static and dynamic memory allocation. ",
    "Q10) What are page faults and how are they handled by the operating system?",
    "Q11) What factors determine the size of page frames in a virtual memory system? ",
    "Q12) Describe the role of a page table in virtual memory management. ",
    "Q13) Compare and contrast demand paging and anticipatory paging techniques. ",
    "Q14) What are some potential benefits and drawbacks of using virtual memory? ",
    "Q15) Explain the concept of memory caches and their levels in a computer system.",
    "Q16) Discuss the challenges of memory management in multi-threaded and concurrent programming environments. ",
    "Q17 What are some memory management considerations for embedded systems with limited resources? ",
    "Q18) What are some memory management considerations for cloud computing environments with virtual machines and containers?",
    "Q19) Briefly describe the concept of memory-mapped files and their use cases.",
    "Q20) What are some potential future trends in memory management technologies? ",
    "Q21) How does memory management relate to security concerns in computer systems? ",
    "Q22) What are some resources available for further learning about memory management?",
    "Q23) Registers are located in: ",
    "Q24) Registers store:",
    "Q25) The advantage of using registers compared to main memory is:",
    "Q26) Different types of registers have specific purposes. Which register holds the address of the next instruction to be executed?",
    "Q27) Registers are limited in number compared to main memory. This can lead to:",
    "Q28) Techniques like register allocation and spilling aim to: ",
    "Q29) What is the advantage of using general-purpose registers? ",
    "Q30) Techniques like pipelining can utilize registers to: ",
    "Q31) Saving and restoring register values is crucial during: ",
    "Q32) Register windows can be used to:",
    "Q33) Floating-point registers are optimized for: ",
    "Q34) Vector registers are used in specific instructions for: ",
    "Q35) In multi-core processors, register sets can be: ",
    "Q36) Register files on graphics cards play a crucial role in: ",
    "Q37) The design and configuration of registers have a significant impact on:", 
    "Q38) What is the name for the technique of saving register values during context switching in multi-threaded environments? ", 
    "Q39) How can hardware-assisted virtualization technologies leverage registers for efficient virtual machine operation? ",
    "Q40) What are some potential challenges in designing registers for emerging processor architectures like neuromorphic computing? ",
    "Q41) Research in computer architecture often explores novel register designs. What is one potential avenue for future register implementations?",
    "Q42) As technology advances, how might the role of registers evolve in computer systems? ",
    "Q43) What document file format is the default for Microsoft Word?",
    "Q44) What feature in Word allows you to track changes made to a document?",
    "Q45) Which keyboard shortcut inserts a symbol in Word? ",
    "Q46) How can you create a numbered list in Word? ",
    "Q47) What is the purpose of the Header and Footer feature in Word?",
    "Q48) What is the cell address for the cell located in the first row and first column of a spreadsheet? ",
    "Q49) Which function calculates the average of a range of cells in Excel? ",
    "Q50) How can you create a chart in Excel? ",
    "Q51) What is the purpose of conditional formatting in Excel? ",
    "Q52) How can you protect a worksheet in Excel from being edited? ",
    "Q53) What is the default slide layout in PowerPoint? ",
    "Q54) How can you add animation to a slide object in PowerPoint?",
    "Q55) What is the purpose of speaker notes in PowerPoint? ",
    "Q56)  How can you create a hyperlink in PowerPoint that opens a website when clicked? ",
    "Q57) What keyboard shortcut fills a range of cells with the same value? ",
    "Q58) What is the difference between a relative and an absolute cell reference in Excel? ",
    "Q59) How can you create a pivot table in Excel?",
    "Q60) What is the VLOOKUP function used for in Excel? ",
    "Q61) What is the difference between a formula and a function in Excel? ",
    "Q62) What is the purpose of the Slide Sorter view in PowerPoint?",
    "Q63) How can you add a transition effect between slides in PowerPoint? ",
    "Q64) What is the purpose of the Notes view in PowerPoint? ",
    "Q65) How can you add a background image to a slide in PowerPoint?",
    "Q66) What is the purpose of the Presenter View in PowerPoint? ",
    "Q67) What is the primary file format used by Microsoft Access databases? ",
    "Q68) What is a table in an Access database used for? ",
    "Q69) What is a query in Access used for?",
    "Q70) What is a form in Access used for?",
    "Q71) What is a report in Access used for?",
    "Q72) What is the default file format for email messages in Outlook? ",
    "Q73) How can you create a calendar event in Outlook?",
    "Q74) What is the purpose of the Rules feature in Outlook? ",
    "Q75) How can you create a contact in Outlook? ",
    "Q76) What is the difference between BCC and CC in Outlook when sending emails? ",
    "Q77) What is the default start menu type in Windows 11? ",
    "Q78) What is Snap Layouts used for in Windows 11?",
    "Q79) What is the new Widgets feature in Windows 11?",
    "Q80) How can you quickly access system settings in Windows 11?",
    "Q81) What is the default file explorer view in Windows 11?",
    "Q82) What does Windows Security include?",
    "Q83) What is the purpose of Smart App Control in Windows 11? ",
    "Q84) What is the default web browser in Windows 11? ",
    "Q85) How can you manage app permissions in Windows 11? ",
    "Q86) What does the Alt + F4 keyboard shortcut do in Windows 11?",
    "Q87) What is Task Manager used for in Windows 11? ",
    "Q88) What is the purpose of PowerShell in Windows 11?",
    "Q89) How can you access the System Restore feature in Windows 11? ",
    "Q90) What is the System File Checker (SFC) used for in Windows 11? ",
    "Q91) What does the Ctrl + Alt + Delete keyboard shortcut do in Windows 11?",
    "Q92) What is the official codename for Windows 11? ",
    "Q93) What is the new Auto HDR feature in Windows 11 designed to do? ",
    "Q94) What is the difference between Windows 11 Home and Windows 11 Pro?",
    "Q95) What is the future of Windows 11 development? ",
    "Q96) Where is the BIOS physically located on a computer? ",
    "Q97) What is the main function of the BIOS?",
    "Q98) What is the POST (Power-On Self-Test)?",
    "Q99) What is the CMOS battery used for?",
    "Q100)How can you access the BIOS setup menu?",
    ]
    
    
    