export const questions=[
"Q1) How does IGMP (Internet Group Management Protocol) support multicast communication in the Transport layer?",
"Q2) What vulnerabilities can Transport layer protocols like TCP be exposed to, and how can secure protocols like TLS/SSL mitigate them?",
"Q3) How can network administrators leverage Transport layer features to optimize network performance for specific applications?",
"Q4) How might Transport layer protocols need to adapt to the growth of Internet of Things (IoT) devices with diverse and dynamic network connections?",
"Q5) What potential role could Software-Defined Networking (SDN) play in enhancing the Transport layer and its management in future networks?",
"Q6) How might emerging network technologies like 5G and satellite internet impact the design and implementation of Transport layer protocols?",
"Q7) What type of media does the Physical layer primarily deal with?",
"Q8) Which of these is NOT a primary function of the Physical layer?",
"Q9) What is the difference between bit rate and baud rate?",
"Q10) What is the purpose of line coding in the Physical layer?",
"Q11) What are some common types of physical media used in networks?",
"Q12) What is the primary difference between analog and digital signaling?",
"Q13) What is the purpose of signal modulation in the Physical layer?",
"Q14) Which of these is NOT a common type of modulation technique used in the Physical layer?",
"Q15) What is the effect of noise and interference on data transmission in the Physical layer?",
"Q16) What are some techniques used in the Physical layer to mitigate the effects of noise and interference?",
"Q17 What is the purpose of physical layer standards like IEEE 802.3 (Ethernet)?",
"Q18) What is the difference between full-duplex and half-duplex communication in the Physical layer?",
"Q19) What is the role of physical layer hubs in network communication?",
"Q20) What are some advantages and disadvantages of using wireless connections in the Physical layer compared to wired connections?",
"Q21) How does the Physical layer contribute to the overall security of network communication?",
"Q22) What are some common Physical layer issues that can affect network performance?",
"Q23) What are some tools and techniques that can be used to troubleshoot Physical layer problems?",
"Q24) How can Physical layer parameters be optimized to improve network performance?",
"Q25)  What are some challenges associated with implementing emerging Physical layer technologies like Li-Fi or mmWave communications?",
"Q26) How might the role of the Physical layer evolve in the future with the increasing adoption of technologies like the Internet of Things (IoT) and edge computing?",
"Q27) What potential ethical considerations should be addressed in the development and implementation of new Physical layer technologies?",
"Q28) What is the purpose of encoding and decoding data at the Physical layer?",
"Q29)  How does the Physical layer interact with the Data Link layer in the OSI model?",
"Q30) What are some common techniques used for error detection and correction at the Physical layer?",
"Q31) What are the implications of choosing a higher or lower data rate at the Physical layer?",
"Q32) What is the difference between analog and digital transmission mediums, and what are their respective advantages and disadvantages in the Physical layer?",
"Q33)  What factors influence the choice of a specific modulation technique (e.g., AM, FM, AM) in the Physical layer?",
"Q34)  How does data rate relate to bandwidth in the Physical layer?",
"Q35)  What is the purpose of channel equalization in the Physical layer?",
"Q36)  What are some common types of noise that can affect data transmission in the Physical layer?",
"Q37) What impact can these different types of noise have on data transmission at the Physical layer?", 
"Q38) How can network administrators mitigate the effects of noise and interference in the Physical layer?", 
"Q39) Why are Physical layer standards like IEEE 802.11 (Wi-Fi) important for network communication?",
"Q40) What is the difference between point-to-point and multipoint connections in the Physical layer?",
"Q41) What are some of the benefits and challenges of using wireless connections like Wi-Fi or Bluetooth compared to wired connections like Ethernet cables?",
"Q42) How does the Physical layer contribute to network security overall?",
"Q43) What is the difference between a three-way handshake and a four-way handshake in TCP connection establishment?",
"Q44) How does TCP utilize se quence numbers and acknowledgment numbers to ensure reliable data delivery?",
"Q45)  What is the purpose of Naggle's algorithm in TCP congestion control?",
"Q46) What is the concept of Maximum Segment Size (MSS) in Transport layer protocols and how does it impact performance?",
"Q47) What techniques can be used to enhance security at the Transport layer?",
"Q48)  How can you identify that packet loss might be occurring at the Transport layer?",
"Q49) What tools can be used to analyze and troubleshoot Transport layer traffic?",
"Q50) What factors can contribute to poor performance at the Transport layer?",
"Q51)  How can you optimize Transport layer performance for specific applications?",
"Q52) Which SDLC model is iterative and delivers working software in increments?",
"Q53) What document outlines the system architecture and design?",
"Q54) Which phase focuses on identifying and testing defects in the software?",
"Q55) How many core processes are defined in the Capability Maturity Model Integration (CMMI)?",
"Q56) Which principle advocates for breaking down complex tasks into smaller, manageable units?",
"Q57) What programming paradigm focuses on data and how it is manipulated?",
"Q58) Which data structure allows for random access of elements by index?",
"Q59) What is the concept of writing code that can be reused in different programs?",
"Q60) Which design pattern promotes loose coupling and observer-based communication?",
"Q61) What testing method focuses on the internal structure of the software?",
"Q62) Which type of testing verifies that the software meets defined requirements?",
"Q63)What metric measures the percentage of defects found in a specific testing phase?",
"Q64) What quality attribute ensures the software remains operational under unexpected conditions?",
"Q65) Which tool helps manage bug reports and track their resolution?",
"Q66) Which version control system stores code changes in a series of snapshots?",
"Q67) What practice automatically builds and tests software after each code change?",
"Q68) Which deployment strategy releases new features gradually to a subset of users?",
"Q69) What tool automates the configuration and provisioning of infrastructure?",
"Q70) What security practice involves encrypting data at rest and in transit?",
"Q71) What programming language is commonly used for building web applications?",
"Q72) Which framework provides a complete structure for building web applications in Python?",
"Q73) What database management system is popular for storing relational data?",
"Q74) Which cloud platform offers serverless computing services?",
"Q75) What open-source project management tool is widely used for agile development?",
"Q76) Which modeling technique visualizes the flow of data within a system?",
"Q77) What type of analysis identifies potential risks and vulnerabilities in a software system?",

"Q78) Which technique helps break down complex requirements into smaller, more manageable ones?",
"Q79) What diagram represents the relationships and interactions between objects in a system?",
"Q80) Which metric calculates the average number of defects found per unit of effort?",
"Q81) What principle emphasizes designing software that is easy to understand, modify, and extend?",
"Q82) Which practice involves writing clear and concise documentation for users and developers?",
"Q83) What concept refers to the gradual decline in software quality due to accumulated technical debt?",
"Q84) Which practice involves regularly reviewing and adapting the software development process to improve efficiency?",
"Q85) What principle emphasizes choosing the simplest solution that meets the requirements?",
"Q86) What security practice involves identifying and patching vulnerabilities in software before they are exploited?",
"Q87) Which ethical principle emphasizes protecting user privacy and avoiding the unauthorized collection of data?",
"Q88) What legal framework regulates the collection and use of personal data in the European Union?",
"Q89) Which principle emphasizes developing software that is fair and unbiased, minimizing harm and respecting human values?",
"Q90)What ethical standard emphasizes delivering software that meets user expectations and provides adequate customer support?",
"Q91) What emerging technology promises to revolutionize software development by using machine learning to write code?",
"Q92) What is the term for the increasing complexity and interconnectedness of software systems?",
"Q93) What movement emphasizes collaboration and communication between developers and stakeholders throughout the software development process?",
"Q94)What open-source platform for code sharing and collaboration is popular among developers?",
"Q95)What term refers to the practice of developing software applications for mobile devices?",
"Q96) Which distributed data storage system replicates data across multiple nodes for increased fault tolerance and scalability?",
"Q97) What containerization technology packages software into isolated units with their own dependencies, enabling portable and efficient deployment?",
"Q98) Which microservices architecture principle advocates for dividing a large application into smaller, independent services?",
"Q99) What type of AI model learns from data without explicit programming, improving its performance over time?",
"Q100) Which invention is considered the first mechanical computer?",
]